org.gradle.jvmargs=-Xmx2G

# Mod version
paradiseLostVersion=2.4.0-beta+1.21.0

minecraftVersion=1.21
yarnMappings=1.21+build.9
loaderVersion=0.16.7
javaVersion=21

# Dependencies
fabricVersion=0.102.0+1.21
customPortalApiVersion=0.0.1-beta67-1.21
cardinalComponentsVersion=6.1.0
fabricAsmVersion=2.3
