org.gradle.jvmargs=-Xmx2G

# Mod version
paradiseLostVersion=2.4.2-beta+1.21.2

minecraftVersion=1.21.3
yarnMappings=1.21.3+build.2
loaderVersion=0.19.3
javaVersion=21

# Dependencies
fabricVersion=0.114.1+1.21.3
customPortalApiVersion=0.0.1-beta68-1.21.4
cardinalComponentsVersion=6.2.2
fabricAsmVersion=2.3
sherdsApiVersion=6.0.1
tommylibVersion=28.0.0

#moonlightVersion=1.21-2.29.33-fabric
#everyCompatVersion=1.21-2.11.38-fabric
#stoneZoneVersion=1.21-2.11.16-fabric
