org.gradle.jvmargs=-Xmx2G

# Mod version
paradiseLostVersion=2.4.4-beta+1.21.1-SINYTRA

minecraftVersion=1.21.1
yarnMappings=1.21.1+build.3
loaderVersion=0.17.3
javaVersion=21

# Dependencies
fabricVersion=0.116.12+1.21.1
customPortalApiVersion=0.0.1-beta67-1.21
cardinalComponentsVersion=6.1.0
fabricAsmVersion=2.3
sherdsApiVersion=6.0.3

moonlightVersion=1.21-2.25.5-fabric
everyCompatVersion=1.21-2.11.15-fabric
stoneZoneVersion=1.21-2.11.5-fabric
