name: Feature request
description: Suggest an idea for this project
title: ""
labels: [Feature]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our mod!
        Make sure to leave a helpful title.
        If your request is for an accessibility feature, instead issue an [accessibility report](https://github.com/devs-immortal/Paradise-Lost/issues/new?assignees=&labels=Feature&template=accessibility_report.yml&title=Accessibility%3A+).
  - type: markdown
    attributes:
      value: |
        If you haven't already, bring your idea to our [discord server](https://discord.com/invite/wmMa47n)!
  - type: textarea
    id: feature
    attributes:
      label: Feature
      description: What solution/feature did you come up with?
      placeholder: ex. There should be a...
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Have any relevant screenshots or concept art? Share them!
