package net.id.paradise_lost.world.dimension;

import com.mojang.datafixers.util.Pair;
import net.id.paradise_lost.world.gen.noise.ParadiseLostNoiseSettings;
import net.minecraft.core.Holder;
import net.minecraft.core.HolderGetter;
import net.minecraft.core.registries.Registries;
import net.minecraft.data.worldgen.BootstrapContext;
import net.minecraft.world.level.biome.Biome;
import net.minecraft.world.level.biome.Climate;
import net.minecraft.world.level.biome.MultiNoiseBiomeSource;
import net.minecraft.world.level.dimension.DimensionType;
import net.minecraft.world.level.dimension.LevelStem;
import net.minecraft.world.level.levelgen.NoiseBasedChunkGenerator;
import net.minecraft.world.level.levelgen.NoiseGeneratorSettings;

import java.util.List;

public final class ParadiseLostLevelStem {
    private ParadiseLostLevelStem() {
    }

    public static void bootstrap(BootstrapContext<LevelStem> context) {
        HolderGetter<Biome> biomes = context.lookup(Registries.BIOME);
        HolderGetter<DimensionType> dimTypes = context.lookup(Registries.DIMENSION_TYPE);
        HolderGetter<NoiseGeneratorSettings> noiseSettings = context.lookup(Registries.NOISE_SETTINGS);

        Climate.ParameterList<Holder<Biome>> parameterList = new Climate.ParameterList<>(List.of(
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-1.0F, 1.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    Climate.Parameter.span(-1.2F, -1.05F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.TRADEWINDS_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-1.0F, -0.45F),
                    Climate.Parameter.span(-1.0F, -0.1F),
                    Climate.Parameter.span(-1.05F, 1.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.CONTINENTAL_PLATEAU_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-1.0F, -0.45F),
                    Climate.Parameter.span(-0.1F, 0.3F),
                    Climate.Parameter.span(-1.05F, -0.19F),
                    Climate.Parameter.span(-1.0F, 0.05F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_PLAINS_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-1.0F, -0.45F),
                    Climate.Parameter.span(0.3F, 1.0F),
                    Climate.Parameter.span(-1.05F, 1.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.AUTUMNAL_TUNDRA_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.45F, 0.55F),
                    Climate.Parameter.span(-1.0F, -0.1F),
                    Climate.Parameter.span(-1.05F, 0.03F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_PLAINS_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.45F, 0.2F),
                    Climate.Parameter.span(-0.1F, 0.7F),
                    Climate.Parameter.span(-1.05F, -0.19F),
                    Climate.Parameter.span(-1.0F, 0.05F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.CALCITE_CRAGLANDS_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.45F, 0.2F),
                    Climate.Parameter.span(0.7F, 1.0F),
                    Climate.Parameter.span(-1.05F, -0.19F),
                    Climate.Parameter.span(-1.0F, 0.05F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_FOREST_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.2F, 0.55F),
                    Climate.Parameter.span(-0.1F, 0.1F),
                    Climate.Parameter.span(-1.05F, -0.19F),
                    Climate.Parameter.span(-1.0F, 0.05F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.CALCITE_CRAGLANDS_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.2F, 0.55F),
                    Climate.Parameter.span(0.1F, 0.3F),
                    Climate.Parameter.span(-1.05F, 1.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_FOREST_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.2F, 0.55F),
                    Climate.Parameter.span(0.3F, 0.7F),
                    Climate.Parameter.span(-1.05F, 0.03F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_FOREST_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.2F, 1.0F),
                    Climate.Parameter.span(0.7F, 1.0F),
                    Climate.Parameter.span(-1.05F, -0.19F),
                    Climate.Parameter.span(-1.0F, 0.05F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_THICKET_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.span(-1.0F, -0.1F),
                    Climate.Parameter.span(-1.05F, -0.19F),
                    Climate.Parameter.span(-1.0F, 0.05F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_FOREST_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.span(-0.1F, 0.3F),
                    Climate.Parameter.span(-1.05F, 0.03F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_THICKET_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.span(0.3F, 0.7F),
                    Climate.Parameter.span(-1.05F, 0.03F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_GRAND_GLADE_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-1.0F, -0.45F),
                    Climate.Parameter.span(-0.1F, 0.3F),
                    Climate.Parameter.span(-1.05F, 0.03F),
                    Climate.Parameter.span(0.05F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.CONTINENTAL_PLATEAU_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.45F, -0.15F),
                    Climate.Parameter.span(-0.1F, 1.0F),
                    Climate.Parameter.span(-1.05F, 0.03F),
                    Climate.Parameter.span(0.05F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_SHIELD_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.15F, 0.55F),
                    Climate.Parameter.span(-0.1F, 0.1F),
                    Climate.Parameter.span(-1.05F, 0.03F),
                    Climate.Parameter.span(0.05F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_PLAINS_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.15F, 0.2F),
                    Climate.Parameter.span(0.1F, 1.0F),
                    Climate.Parameter.span(-1.05F, 0.03F),
                    Climate.Parameter.span(0.05F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_SHIELD_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.2F, 0.55F),
                    Climate.Parameter.span(0.7F, 1.0F),
                    Climate.Parameter.span(-1.05F, 0.03F),
                    Climate.Parameter.span(0.05F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_FOREST_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.span(-1.0F, -0.1F),
                    Climate.Parameter.span(-1.05F, 1.0F),
                    Climate.Parameter.span(0.05F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_GRAND_GLADE_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.span(0.7F, 1.0F),
                    Climate.Parameter.span(-1.05F, 1.0F),
                    Climate.Parameter.span(0.05F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_GRAND_GLADE_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-1.0F, -0.45F),
                    Climate.Parameter.span(-0.1F, 0.3F),
                    Climate.Parameter.span(-0.19F, 0.03F),
                    Climate.Parameter.span(-1.0F, -0.2225F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_PLAINS_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.45F, 0.2F),
                    Climate.Parameter.span(-0.1F, 0.7F),
                    Climate.Parameter.span(-0.19F, 0.03F),
                    Climate.Parameter.span(-1.0F, -0.2225F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.CALCITE_CRAGLANDS_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.45F, 0.2F),
                    Climate.Parameter.span(0.7F, 1.0F),
                    Climate.Parameter.span(-0.19F, 1.0F),
                    Climate.Parameter.span(-1.0F, -0.2225F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_FOREST_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.2F, 0.55F),
                    Climate.Parameter.span(-0.1F, 0.1F),
                    Climate.Parameter.span(-0.19F, 0.03F),
                    Climate.Parameter.span(-1.0F, -0.2225F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.CALCITE_CRAGLANDS_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.2F, 0.55F),
                    Climate.Parameter.span(0.7F, 1.0F),
                    Climate.Parameter.span(-0.19F, 1.0F),
                    Climate.Parameter.span(-1.0F, -0.2225F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_THICKET_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.span(-1.0F, -0.1F),
                    Climate.Parameter.span(-0.19F, 0.03F),
                    Climate.Parameter.span(-1.0F, -0.2225F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_FOREST_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.span(0.7F, 1.0F),
                    Climate.Parameter.span(-0.19F, 0.03F),
                    Climate.Parameter.span(-1.0F, -0.2225F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_THICKET_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-1.0F, -0.45F),
                    Climate.Parameter.span(-0.1F, 0.3F),
                    Climate.Parameter.span(-0.19F, 0.03F),
                    Climate.Parameter.span(-0.2225F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.CONTINENTAL_PLATEAU_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.45F, -0.15F),
                    Climate.Parameter.span(-0.1F, 1.0F),
                    Climate.Parameter.span(-0.19F, 0.03F),
                    Climate.Parameter.span(-0.2225F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_SHIELD_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.15F, 0.55F),
                    Climate.Parameter.span(-0.1F, 0.1F),
                    Climate.Parameter.span(-0.19F, 0.03F),
                    Climate.Parameter.span(-0.2225F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_PLAINS_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.15F, 0.2F),
                    Climate.Parameter.span(0.1F, 1.0F),
                    Climate.Parameter.span(-0.19F, 0.03F),
                    Climate.Parameter.span(-0.2225F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_SHIELD_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.2F, 0.55F),
                    Climate.Parameter.span(0.7F, 1.0F),
                    Climate.Parameter.span(-0.19F, 0.03F),
                    Climate.Parameter.span(-0.2225F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_FOREST_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.span(-1.0F, -0.1F),
                    Climate.Parameter.span(-0.19F, 1.0F),
                    Climate.Parameter.span(-0.2225F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_GRAND_GLADE_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.span(0.7F, 1.0F),
                    Climate.Parameter.span(-0.19F, 1.0F),
                    Climate.Parameter.span(-0.2225F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_GRAND_GLADE_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-1.0F, -0.45F),
                    Climate.Parameter.span(-0.1F, 1.0F),
                    Climate.Parameter.span(0.03F, 1.0F),
                    Climate.Parameter.span(-1.0F, 0.45F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.AUTUMNAL_TUNDRA_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.45F, 0.2F),
                    Climate.Parameter.span(-1.0F, -0.35F),
                    Climate.Parameter.span(0.03F, 1.0F),
                    Climate.Parameter.span(-1.0F, 0.45F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.WISTERIA_WOODS_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.45F, 0.2F),
                    Climate.Parameter.span(-0.35F, -0.1F),
                    Climate.Parameter.span(0.03F, 1.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_PLAINS_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.45F, 0.2F),
                    Climate.Parameter.span(-0.1F, 1.0F),
                    Climate.Parameter.span(0.03F, 1.0F),
                    Climate.Parameter.span(-1.0F, 0.45F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_FOREST_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.2F, 0.55F),
                    Climate.Parameter.span(-1.0F, -0.35F),
                    Climate.Parameter.span(0.03F, 1.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_PLAINS_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.2F, 0.55F),
                    Climate.Parameter.span(-0.35F, 0.3F),
                    Climate.Parameter.span(0.03F, 1.0F),
                    Climate.Parameter.span(-1.0F, 0.45F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_FOREST_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.2F, 0.55F),
                    Climate.Parameter.span(0.3F, 1.0F),
                    Climate.Parameter.span(0.03F, 1.0F),
                    Climate.Parameter.span(-1.0F, 0.45F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_THICKET_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.span(-1.0F, -0.1F),
                    Climate.Parameter.span(0.03F, 1.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_GRAND_GLADE_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.span(-0.1F, 0.1F),
                    Climate.Parameter.span(0.03F, 1.0F),
                    Climate.Parameter.span(-1.0F, 0.45F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_GRAND_GLADE_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.span(0.1F, 0.3F),
                    Climate.Parameter.span(0.03F, 1.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_THICKET_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.span(0.3F, 0.7F),
                    Climate.Parameter.span(0.03F, 1.0F),
                    Climate.Parameter.span(-1.0F, 0.45F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_THICKET_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.span(0.7F, 1.0F),
                    Climate.Parameter.span(0.03F, 1.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_GRAND_GLADE_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-1.0F, -0.45F),
                    Climate.Parameter.span(-0.1F, 0.3F),
                    Climate.Parameter.span(0.03F, 0.8F),
                    Climate.Parameter.span(0.45F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.CONTINENTAL_PLATEAU_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.45F, 0.55F),
                    Climate.Parameter.span(-1.0F, -0.1F),
                    Climate.Parameter.span(0.03F, 0.8F),
                    Climate.Parameter.span(0.45F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_PLAINS_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.45F, -0.15F),
                    Climate.Parameter.span(-0.1F, 1.0F),
                    Climate.Parameter.span(0.03F, 0.8F),
                    Climate.Parameter.span(0.45F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_SHIELD_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.15F, 0.55F),
                    Climate.Parameter.span(-0.1F, 0.1F),
                    Climate.Parameter.span(0.03F, 0.8F),
                    Climate.Parameter.span(0.45F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_PLAINS_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.15F, 0.2F),
                    Climate.Parameter.span(0.1F, 1.0F),
                    Climate.Parameter.span(0.03F, 0.8F),
                    Climate.Parameter.span(0.45F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_SHIELD_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.2F, 0.55F),
                    Climate.Parameter.span(0.3F, 1.0F),
                    Climate.Parameter.span(0.03F, 0.8F),
                    Climate.Parameter.span(0.45F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_FOREST_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.span(-0.1F, 0.3F),
                    Climate.Parameter.span(0.03F, 0.8F),
                    Climate.Parameter.span(0.45F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_THICKET_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.span(0.3F, 1.0F),
                    Climate.Parameter.span(0.03F, 0.8F),
                    Climate.Parameter.span(0.45F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_GRAND_GLADE_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-1.0F, -0.45F),
                    Climate.Parameter.span(-0.1F, 1.0F),
                    Climate.Parameter.span(0.8F, 1.0F),
                    Climate.Parameter.span(0.45F, 0.55F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.AUTUMNAL_TUNDRA_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.45F, 0.2F),
                    Climate.Parameter.span(-1.0F, -0.35F),
                    Climate.Parameter.span(0.8F, 1.0F),
                    Climate.Parameter.span(0.45F, 0.55F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.WISTERIA_WOODS_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.45F, 0.2F),
                    Climate.Parameter.span(-0.1F, 1.0F),
                    Climate.Parameter.span(0.8F, 1.0F),
                    Climate.Parameter.span(0.45F, 0.55F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_FOREST_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.2F, 0.55F),
                    Climate.Parameter.span(-0.35F, 0.3F),
                    Climate.Parameter.span(0.8F, 1.0F),
                    Climate.Parameter.span(0.45F, 0.55F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_FOREST_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.2F, 0.55F),
                    Climate.Parameter.span(0.3F, 1.0F),
                    Climate.Parameter.span(0.8F, 1.0F),
                    Climate.Parameter.span(0.45F, 0.55F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_THICKET_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.span(-0.1F, 0.1F),
                    Climate.Parameter.span(0.8F, 1.0F),
                    Climate.Parameter.span(0.45F, 0.55F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_GRAND_GLADE_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.span(0.3F, 0.7F),
                    Climate.Parameter.span(0.8F, 1.0F),
                    Climate.Parameter.span(0.45F, 0.55F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_THICKET_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-1.0F, -0.45F),
                    Climate.Parameter.span(-0.1F, 0.3F),
                    Climate.Parameter.span(0.8F, 1.0F),
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.CONTINENTAL_PLATEAU_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.45F, 0.55F),
                    Climate.Parameter.span(-1.0F, -0.1F),
                    Climate.Parameter.span(0.8F, 1.0F),
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_PLAINS_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.45F, -0.15F),
                    Climate.Parameter.span(-0.1F, 1.0F),
                    Climate.Parameter.span(0.8F, 1.0F),
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_SHIELD_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.15F, 0.55F),
                    Climate.Parameter.span(-0.1F, 0.1F),
                    Climate.Parameter.span(0.8F, 1.0F),
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_PLAINS_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(-0.15F, 0.2F),
                    Climate.Parameter.span(0.1F, 1.0F),
                    Climate.Parameter.span(0.8F, 1.0F),
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_SHIELD_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.2F, 0.55F),
                    Climate.Parameter.span(0.3F, 1.0F),
                    Climate.Parameter.span(0.8F, 1.0F),
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_FOREST_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.span(-0.1F, 0.3F),
                    Climate.Parameter.span(0.8F, 1.0F),
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_THICKET_KEY)),
                Pair.of(Climate.parameters(
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.span(0.3F, 1.0F),
                    Climate.Parameter.span(0.8F, 1.0F),
                    Climate.Parameter.span(0.55F, 1.0F),
                    Climate.Parameter.point(0.0F),
                    Climate.Parameter.span(-1.0F, 1.0F),
                    0.0F), biomes.getOrThrow(ParadiseLostBiomes.HIGHLANDS_GRAND_GLADE_KEY))
        ));

        MultiNoiseBiomeSource biomeSource = MultiNoiseBiomeSource.createFromList(parameterList);
        NoiseBasedChunkGenerator chunkGenerator = new NoiseBasedChunkGenerator(
                biomeSource,
                noiseSettings.getOrThrow(ParadiseLostNoiseSettings.NOISE)
        );
        context.register(
                ParadiseLostDimension.OPTIONS_KEY,
                new LevelStem(dimTypes.getOrThrow(ParadiseLostDimension.DIMENSION_TYPE), chunkGenerator)
        );
    }
}
