name: Java CI with Gradle

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  should_run:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check if new commits exist
        id: get_commit
        run: | 
          if git log --since="6 hours ago" --pretty=format:"%h - %an" | grep -q "-"; then
              echo "should_run=true" >> $GITHUB_ENV
          else
              echo "should_run=false" >> $GITHUB_ENV
          fi

  build:
    runs-on: ubuntu-latest
    if: ${{ needs.should_run.outputs.should_run == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ./build/libs/

      - name: Release Build
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.md
          files: "./build/libs/**"

      - name: Build Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Build Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Build Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Build Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Build Cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          severity: warn
          details: Build Cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

  checkstyle:
    runs-on: ubuntu-latest
    if: ${{ needs.should_run.outputs.should_run == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Checkstyle with Gradle
        run: ./gradlew checkstyleMain

      - name: Checkstyle Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          color: '#ff5500'
          details: Checkstyle Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
